// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqfplzjkbetpzauiwleq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxZnBsemprYmV0cHphdWl3bGVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5Nzk2MTYsImV4cCI6MjA2MjU1NTYxNn0.XO1D2o2iLVNFNrjdUBYBuJ0wCiKgm5JnQm5JKiIPL8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);